package org.redeye.valen.game.spacemarines2.types;

import be.twofold.valen.core.texture.*;

public enum PictureFormat {
    PCT_FORMAT_ARGB8888,
    PCT_FORMAT_ARGB4444,
    PCT_FORMAT_RGB888,
    PCT_FORMAT_A8,
    PCT_FORMAT_RGB332,
    PCT_FORMAT_RGB565,
    PCT_FORMAT_ARGB8332,
    PCT_FORMAT_ARGB1555,
    PCT_FORMAT_I8,
    PCT_FORMAT_AI44,
    PCT_FORMAT_AI88,
    PCT_FORMAT_UV88,
    PCT_FORMAT_DXT1_OPAQUE,
    PCT_FORMAT_DXT1_TRANSPARENT,
    PCT_FORMAT_DXT2,
    PCT_FORMAT_DXT3,
    PCT_FORMAT_DXT4,
    PCT_FORMAT_DXT5,
    PCT_FORMAT_P8,
    PCT_FORMAT_P4,
    PCT_FORMAT_AP8,
    PCT_FORMAT_AP4,
    PCT_FORMAT_XRGB8888,
    PCT_FORMAT_ARGB7888R,
    PCT_FORMAT_ARGB1555R,
    PCT_FORMAT_RGB555R,
    PCT_FORMAT_RGB888R,
    PCT_FORMAT_SWIZ_ARGB8888,
    PCT_FORMAT_SWIZ_ARGB4444,
    PCT_FORMAT_SWIZ_RGB888,
    PCT_FORMAT_SWIZ_RGB565,
    PCT_FORMAT_SWIZ_ARGB1555,
    PCT_FORMAT_SWIZ_UV88,
    PCT_FORMAT_SWIZ_XRGB8888,
    PCT_FORMAT_SWIZ_P8,
    PCT_FORMAT_SWIZ_AP8,
    PCT_FORMAT_DXN,
    PCT_FORMAT_DXT5A,
    PCT_FORMAT_RGBA16161616F,
    PCT_FORMAT_ARGB16161616S,
    PCT_FORMAT_ARGB16161616U,
    PCT_FORMAT_R16F,
    PCT_FORMAT_R32F,
    PCT_FORMAT_RGB323232F,
    PCT_FORMAT_SWIZ_ARGB8888U,
    PCT_FORMAT_R9G9B9E5_SHAREDEXP,
    PCT_FORMAT_R8U,
    PCT_FORMAT_R10G10B10A2_UNORM,
    PCT_FORMAT_R32U,
    PCT_FORMAT_BC6U,
    PCT_FORMAT_BC6S,
    PCT_FORMAT_BC7,
    PCT_FORMAT_BC7A,
    PCT_FORMAT_R16G16F,
    PCT_FORMAT_R16G16,
    PCT_FORMAT_R16,
    PCT_FORMAT_R32G32U,
    PCT_FORMAT_RGBA32323232F,
    PCT_FORMAT_R32G32B32A32U,
    PCT_FORMAT_R32G32B32A32S,
    PCT_FORMAT_R32G32B32U,
    PCT_FORMAT_R32G32B32S,
    PCT_FORMAT_R16G16U,
    PCT_FORMAT_R8G8U,
    PCT_FORMAT_SWIZ_ARGB8888S,
    PCT_FORMAT_MAX;

    public TextureFormat mapToTextureFormat() {
        return switch (this) {
            case PCT_FORMAT_BC7, PCT_FORMAT_BC7A -> TextureFormat.BC7_SRGB;
            case PCT_FORMAT_DXT1_OPAQUE -> TextureFormat.BC1_SRGB;
            case PCT_FORMAT_DXT2, PCT_FORMAT_DXT3 -> TextureFormat.BC2_SRGB;
            case PCT_FORMAT_DXT4, PCT_FORMAT_DXT5 -> TextureFormat.BC3_SRGB;
            case PCT_FORMAT_DXT5A -> TextureFormat.BC4_UNORM;
            case PCT_FORMAT_DXN -> TextureFormat.BC5_UNORM;
            case PCT_FORMAT_XRGB8888 -> TextureFormat.R8G8B8A8_UNORM;
            default -> {
                throw new IllegalStateException("Unsupported format: " + this);
            }
        };
    }
}
