#
# Root logger level
.level=INFO
be.twofold.level=FINE
#
# Console handler. File handler is done by FileHandler.java
handlers=be.twofold.valen.core.util.logging.StdOutHandler
#
# Console handler configuration
be.twofold.valen.core.util.logging.StdOutHandler.formatter=be.twofold.valen.core.util.logging.ColoredFormatter
be.twofold.valen.core.util.logging.StdOutHandler.level=ALL
