package be.twofold.valen.core.compression.oodle.ffm;// Generated by jextract

import java.lang.foreign.*;

public final class OodleConfigValues {
    private static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_INT.withByteAlignment(1).withName("m_OodleLZ_LW_LRM_step"),
        ValueLayout.JAVA_INT.withByteAlignment(1).withName("m_OodleLZ_LW_LRM_hashLength"),
        ValueLayout.JAVA_INT.withByteAlignment(1).withName("m_OodleLZ_LW_LRM_jumpbits"),
        ValueLayout.JAVA_INT.withByteAlignment(1).withName("m_OodleLZ_Decoder_Max_Stack_Size"),
        ValueLayout.JAVA_INT.withByteAlignment(1).withName("m_OodleLZ_Small_Buffer_LZ_Fallback_Size_Unused"),
        ValueLayout.JAVA_INT.withByteAlignment(1).withName("m_OodleLZ_BackwardsCompatible_MajorVersion"),
        ValueLayout.JAVA_INT.withByteAlignment(1).withName("m_oodle_header_version")
    ).withName("OodleConfigValues");

    private static final ValueLayout.OfInt m_OodleLZ_LW_LRM_step$LAYOUT = (ValueLayout.OfInt) LAYOUT.select(MemoryLayout.PathElement.groupElement("m_OodleLZ_LW_LRM_step"));
    private static final ValueLayout.OfInt m_OodleLZ_LW_LRM_hashLength$LAYOUT = (ValueLayout.OfInt) LAYOUT.select(MemoryLayout.PathElement.groupElement("m_OodleLZ_LW_LRM_hashLength"));
    private static final ValueLayout.OfInt m_OodleLZ_LW_LRM_jumpbits$LAYOUT = (ValueLayout.OfInt) LAYOUT.select(MemoryLayout.PathElement.groupElement("m_OodleLZ_LW_LRM_jumpbits"));
    private static final ValueLayout.OfInt m_OodleLZ_Decoder_Max_Stack_Size$LAYOUT = (ValueLayout.OfInt) LAYOUT.select(MemoryLayout.PathElement.groupElement("m_OodleLZ_Decoder_Max_Stack_Size"));
    private static final ValueLayout.OfInt m_OodleLZ_Small_Buffer_LZ_Fallback_Size_Unused$LAYOUT = (ValueLayout.OfInt) LAYOUT.select(MemoryLayout.PathElement.groupElement("m_OodleLZ_Small_Buffer_LZ_Fallback_Size_Unused"));
    private static final ValueLayout.OfInt m_OodleLZ_BackwardsCompatible_MajorVersion$LAYOUT = (ValueLayout.OfInt) LAYOUT.select(MemoryLayout.PathElement.groupElement("m_OodleLZ_BackwardsCompatible_MajorVersion"));
    private static final ValueLayout.OfInt m_oodle_header_version$LAYOUT = (ValueLayout.OfInt) LAYOUT.select(MemoryLayout.PathElement.groupElement("m_oodle_header_version"));

    private final MemorySegment segment;

    public OodleConfigValues(Arena arena) {
        segment = arena.allocate(LAYOUT);
    }

    public MemorySegment segment() {
        return segment;
    }

    public int m_OodleLZ_LW_LRM_step() {
        return segment.get(m_OodleLZ_LW_LRM_step$LAYOUT, 0);
    }

    public int m_OodleLZ_LW_LRM_hashLength() {
        return segment.get(m_OodleLZ_LW_LRM_hashLength$LAYOUT, 4);
    }

    public int m_OodleLZ_LW_LRM_jumpbits() {
        return segment.get(m_OodleLZ_LW_LRM_jumpbits$LAYOUT, 8);
    }

    public int m_OodleLZ_Decoder_Max_Stack_Size() {
        return segment.get(m_OodleLZ_Decoder_Max_Stack_Size$LAYOUT, 12);
    }

    public int m_OodleLZ_Small_Buffer_LZ_Fallback_Size_Unused() {
        return segment.get(m_OodleLZ_Small_Buffer_LZ_Fallback_Size_Unused$LAYOUT, 16);
    }

    public int m_OodleLZ_BackwardsCompatible_MajorVersion() {
        return segment.get(m_OodleLZ_BackwardsCompatible_MajorVersion$LAYOUT, 20);
    }

    public int m_oodle_header_version() {
        return segment.get(m_oodle_header_version$LAYOUT, 24);
    }
}
