package be.twofold.valen.game.greatcircle.reader.resources;

import wtf.reversed.toolbox.io.*;
import wtf.reversed.toolbox.util.*;

import java.io.*;

public enum ResourcesVariation implements ValueEnum<Integer> {
    RES_VAR_NONE(0),
    RES_VAR_DEBUG(24),
    RES_VAR_DEV(25),
    RES_VAR_RETAIL(26),
    RES_VAR_QUALITY_LOW(100),
    RES_VAR_QUALITY_MEDIUM(101),
    RES_VAR_QUALITY_HIGH(102),
    RES_VAR_RENDERPROG_VULKAN_PC_BASE(33),
    RES_VAR_RENDERPROG_VULKAN_PC_AMD(34),
    RES_VAR_RENDERPROG_VULKAN_PC_NVIDIA(35),
    RES_VAR_RENDERPROG_VULKAN_PC_INTEL(36),
    RES_VAR_RENDERPROG_D3D12_PC_BASE(37),
    RES_VAR_RENDERPROG_PS4_BASE_SRT(42),
    RES_VAR_RENDERPROG_PS4_NEO_SRT(43),
    RES_VAR_RENDERPROG_XB1_BASE_D3D12(44),
    RES_VAR_RENDERPROG_SWITCH(48),
    RES_VAR_RENDERPROG_VULKAN_YETI(49),
    RES_VAR_RENDERPROG_SCARLETT_D3D12(50),
    RES_VAR_RENDERPROG_LIME_BASE(51),
    RES_VAR_RENDERPROG_DUMMY(52),
    RES_VAR_RENDERPROG_SCARLETT_D3D12_LOCKHART(53),
    RES_VAR_RENDERPROG_LIME_PLUS(54),
    RES_VAR_RENDERPROG_VULKAN_PC_BASE_RETAIL(300),
    RES_VAR_RENDERPROG_VULKAN_PC_AMD_RETAIL(301),
    RES_VAR_RENDERPROG_VULKAN_PC_NVIDIA_RETAIL(302),
    RES_VAR_RENDERPROG_VULKAN_PC_INTEL_RETAIL(303),
    RES_VAR_RENDERPROG_D3D12_PC_BASE_RETAIL(304),
    RES_VAR_RENDERPROG_PS4_BASE_SRT_RETAIL(305),
    RES_VAR_RENDERPROG_PS4_NEO_SRT_RETAIL(306),
    RES_VAR_RENDERPROG_XB1_BASE_D3D12_RETAIL(307),
    RES_VAR_RENDERPROG_SWITCH_RETAIL(311),
    RES_VAR_RENDERPROG_VULKAN_YETI_RETAIL(312),
    RES_VAR_RENDERPROG_SCARLETT_D3D12_RETAIL(313),
    RES_VAR_RENDERPROG_LIME_BASE_RETAIL(314),
    RES_VAR_RENDERPROG_SCARLETT_D3D12_LOCKHART_RETAIL(315),
    RES_VAR_RENDERPROG_LIME_PLUS_RETAIL(316),
    RES_VAR_HK_GEN_64(64),
    RES_VAR_HK_MSVC_64(65),
    RES_VAR_PLATFORM_WIN(200),
    RES_VAR_PLATFORM_WIN32(201),
    RES_VAR_PLATFORM_WIN64(202),
    RES_VAR_PLATFORM_LINUX(210),
    RES_VAR_PLATFORM_LINUX32(211),
    RES_VAR_PLATFORM_LINUX64(212),
    RES_VAR_PLATFORM_PS4(220),
    RES_VAR_PLATFORM_PS4_NEO(221),
    RES_VAR_PLATFORM_XB1(230),
    RES_VAR_PLATFORM_XB1_SCORPIO(231),
    RES_VAR_PLATFORM_SWITCH(240),
    RES_VAR_PLATFORM_SCARLETT(241),
    RES_VAR_PLATFORM_LIME(242),
    RES_VAR_PLATFORM_LIME_BASE(243),
    RES_VAR_PLATFORM_LIME_PLUS(244),
    RES_VAR_PLATFORM_KIWI(245),
    RES_VAR_PLATFORM_RESERVED_DO_NOT_USE(299),
    RES_VAR_LANGUAGE_AR_AE(400),
    RES_VAR_LANGUAGE_AR_SA(401),
    RES_VAR_LANGUAGE_BG_BG(402),
    RES_VAR_LANGUAGE_CS_CZ(403),
    RES_VAR_LANGUAGE_DA_DK(404),
    RES_VAR_LANGUAGE_DE_DE(405),
    RES_VAR_LANGUAGE_EN_GB(406),
    RES_VAR_LANGUAGE_EN_US(407),
    RES_VAR_LANGUAGE_ES_ES(408),
    RES_VAR_LANGUAGE_ES_MX(409),
    RES_VAR_LANGUAGE_FI_FI(410),
    RES_VAR_LANGUAGE_FR_CA(411),
    RES_VAR_LANGUAGE_FR_FR(412),
    RES_VAR_LANGUAGE_EL_GR(413),
    RES_VAR_LANGUAGE_HE_IL(414),
    RES_VAR_LANGUAGE_HU_HU(415),
    RES_VAR_LANGUAGE_IT_IT(416),
    RES_VAR_LANGUAGE_JA_JP(417),
    RES_VAR_LANGUAGE_KO_KR(418),
    RES_VAR_LANGUAGE_NL_NL(419),
    RES_VAR_LANGUAGE_NB_NO(420),
    RES_VAR_LANGUAGE_NO_NO(421),
    RES_VAR_LANGUAGE_PL_PL(422),
    RES_VAR_LANGUAGE_PT_BR(423),
    RES_VAR_LANGUAGE_PT_PT(424),
    RES_VAR_LANGUAGE_RO_RO(425),
    RES_VAR_LANGUAGE_RU_RU(426),
    RES_VAR_LANGUAGE_SK_SK(427),
    RES_VAR_LANGUAGE_SV_SE(428),
    RES_VAR_LANGUAGE_TH_TH(429),
    RES_VAR_LANGUAGE_TR_TR(430),
    RES_VAR_LANGUAGE_UK_UA(431),
    RES_VAR_LANGUAGE_VI_VN(432),
    RES_VAR_LANGUAGE_ZH_CN(433),
    RES_VAR_LANGUAGE_ZH_HK(434),
    RES_VAR_LANGUAGE_ZH_TW(435),
    RES_VAR_LANGUAGE_ID_ID(436),
    RES_VAR_LANGUAGE_RESERVED_DO_NOT_USE(499),
    ;

    private final int value;

    ResourcesVariation(int value) {
        this.value = value;
    }

    public static ResourcesVariation read(BinarySource source) throws IOException {
        return ValueEnum.fromValue(ResourcesVariation.class, Short.toUnsignedInt(source.readShort()));
    }

    @Override
    public Integer value() {
        return value;
    }
}
